apiVersion: v1
kind: Service
metadata:
  name: user-admin-repo
  namespace: bit_2503
  labels:
    app: user-admin-repo
spec:
  selector:
    app: user-admin-repo
  type: ClusterIP
  ports:
    - name: http-user
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: http-payment
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: http-admin
      protocol: TCP
      port: 8082
      targetPort: 8082
